FROM node:19
WORKDIR /app
COPY back/ .
RUN npx prisma generate
RUN npx dotenv -e .env.test prisma generate

RUN npm run build
COPY back/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

RUN mkdir -p source/audio source/video
RUN mkdir -p var/log

EXPOSE 4000
EXPOSE 9229
CMD ["/app/entrypoint.sh"]
