# watch: https://docs.docker.com/compose/how-tos/file-watch/#action
services:
  frontend:
    image: node:16
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    develop:
      watch:
        - action: sync
          path: ./back/src
          target: /app/src
          ignore:
            - .back/node_modules/
        - action: sync
          path: ./back/__tests__
          target: /app/__tests__
        - action: sync
          path: ./back/prisma
          target: /app/prisma
        - action: rebuild
          path: ./back/package.json
        - action: rebuild
          path: ./back/entrypoint.sh
    ports:
      - "4000:4000"
      - "5555:5555"
      - "9229:9229"
      
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      NODE_ENV: development
      POSTGRES_USER_FILE: /run/secrets/postgres_user 
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    depends_on:
      - db
    

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
  
  whisper:
    image: litongjava/whisper-cpp-server:1.0.0
    container_name: whisper-server
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models
    command: /app/whisper_http_server_base_httplib -m /app/models/whisper-large-v3-french-distil-dec8/ggml-model-q5_0.bin


secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_db:
    file: ./secrets/postgres_db.txt

volumes:
  postgres-data:
  backend-logs: