FROM node:24
WORKDIR /app
COPY back/ .

COPY back/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

RUN npm install
RUN npx prisma generate
RUN mkdir -p source/audio source/video
RUN mkdir -p var/log

EXPOSE 4000
EXPOSE 9229
CMD ["/app/entrypoint.sh"]
