FROM node:16
WORKDIR /app
COPY front/package*.json ./
RUN npm install
COPY back/ .
RUN npx prisma generate

RUN npm run build
COPY back/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 4000
EXPOSE 9229
CMD ["/app/entrypoint.sh"]